export const background = [
  { name: 'normal', color: '#AAA67f' },
  { name: 'fighting', color: '#C12239' },
  { name: 'flying', color: '#A891EC' },
  { name: 'ground', color: '#DEC16B' },
  { name: 'poison', color: '#A43E9E' },
  { name: 'rock', color: '#B69E31' },
  { name: 'bug', color: '#A7B723' },
  { name: 'ghost', color: '#7B62A3' },
  { name: 'steel', color: '#B7B7CE' },
  { name: 'fire', color: '#F25D27' },
  { name: 'water', color: '#4A90DA' },
  { name: 'grass', color: '#7ACB48' },
  { name: 'electric', color: '#F9CF30' },
  { name: 'psychic', color: '#FB5584' },
  { name: 'ice', color: '#9AD6DF' },
  { name: 'dragon', color: '#7037FF' },
  { name: 'dark', color: '#7037FF' },
  { name: 'fairy', color: '#E69EAC' },
  { name: 'unknown', color: '#526677' },
  { name: 'shadow', color: '#4F507B' },
];
